### ISSUE TITLE
Support: Rendering hangul characters

### ISSUE THREAD

**Issue by OmgImAlexis** [DevAndromeda/canvacord#60]
This should show `파랑이#1204`.

<img width="470" alt="Screen Shot 2021-01-03 at 4 35 24 pm" src="https://user-images.githubusercontent.com/6525926/103472836-1712fc80-4de2-11eb-881a-f2b85ad201a4.png">

**Comment by rhydderchc** [comment]
I don't know if this is still relevant or not, but using `sans-serif` you could easily render hangul characters.
Another way of doing it would be registering fonts(based on the language) under the same **family** name and **fallback**.

**Comment by DevAndromeda** [comment]
It is now working properly after switching to [@napi-rs/canvas](https://npm.im/@napi-rs/canvas) since v5.4.x. The new canvas lib by default default looks up for system fonts which should add support for more characters (including emojis).

Ran this test on my windows machine:
![image](https://user-images.githubusercontent.com/46562212/183631201-34cd3993-3c3a-419d-9fdd-8279da2c3491.png)
